# Generated by Django 4.2.6 on 2023-10-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_board_delete_sign_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='faist_name',
            new_name='first_name',
        ),
    ]
